version: "3.5"

volumes:
  realm-server: {}
  um-runs: {}
  umtool-runs: {}
  msr-runs: {}

networks:
  n1:
    external: false

services:
  um:
    image: um-realm-server-1005:${H_WMLAB_FIXES_DATE_TAG}
    container_name: umserver
    hostname: umserver
    networks:
      n1:
        aliases:
          - umserver
    volumes:
      # from 00.commons
      - ../00.commons/lib/unix:${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - um-runs:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      # locals
      - ./scripts/:/mnt/scripts/local/
      #- ${H_WMLAB_LIC_FILE_UM}:${H_WMLAB_LIC_FILE_UM_MOUNT_POINT}
      - realm-server:${H_WMLAB_INSTALL_HOME}/UniversalMessaging/server/${H_WMLAB_REALM_NAME}/:rw
      - ${H_WMLAB_LIC_FILE_UM}:${H_WMLAB_INSTALL_HOME}/UniversalMessaging/server/${H_WMLAB_REALM_NAME}/licence.xml
    environment:
      ### from 00.commons
      # paths
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_INSTALL_HOME=${H_WMLAB_INSTALL_HOME}
      - WMLAB_SUM_HOME=${H_WMLAB_SUM_HOME}
      # switches
      - WMLAB_MONITORING_ON=${H_WMLAB_MONITORING_ON}
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_CTRL_EXEC_STDOUT_ON=${H_WMLAB_CTRL_EXEC_STDOUT_ON}
      # other parameters
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION}
      ### locals
      - WMLAB_REALM_NAME=${H_WMLAB_REALM_NAME}
    ports:
      - "${H_WMLAB_UM_PORT_HOST_PORT}:${H_WMLAB_UM_PORT_GUEST_PORT}"
    entrypoint: /mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/um/entrypoint.sh      
  umtool:
    image: umtool-${H_WMLAB_PRODUCTS_VERSION}:${H_WMLAB_FIXES_DATE_TAG}
    depends_on:
      - um
    container_name: umtool
    hostname: umtool
    networks:
      n1:
        aliases:
          - umtool
    volumes:
      # from 00.commons
      - ../00.commons/lib/unix:${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - umtool-runs:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      # locals
      - ./scripts/:/mnt/scripts/local/
    entrypoint: /mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/umtool/entrypoint.sh      
  msr:
    image: msr-lean-devel-${H_WMLAB_PRODUCTS_VERSION}:${H_WMLAB_FIXES_DATE_TAG}
    depends_on:
      - um
      - umtool
    container_name: msr
    hostname: msr
    networks:
      n1:
        aliases:
          - msr
    volumes:
      # from 00.commons
      - ../00.commons/lib/unix:${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - msr-runs:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      # locals
      - ./scripts/:/mnt/scripts/local/
      # give config
      - ./conf/:/mnt/conf/
      - ./conf/messaging.cnf:${H_WMLAB_INSTALL_HOME}/IntegrationServer/config/messaging.cnf
      - ./conf/application.properties:/tmp/application.properties
      - ./conf/jndi/jndi_external.properties:${H_WMLAB_INSTALL_HOME}/IntegrationServer/config/jndi/jndi_external.properties
      - ./conf/jndi/jndi_local-net.properties:${H_WMLAB_INSTALL_HOME}/IntegrationServer/config/jndi/jndi_local-net.properties
      - ./conf/jms.cnf:${H_WMLAB_INSTALL_HOME}/IntegrationServer/config/jms.cnf
      - ./conf/dispatch.cnf:${H_WMLAB_INSTALL_HOME}/IntegrationServer/config/dispatch.cnf
      # license
      - ${H_WMLAB_LIC_FILE_BPMS_MSR}:/tmp/MSR_LICENSE.xml
      # code
      - ./code/myPackage/:${H_WMLAB_INSTALL_HOME}/IntegrationServer/packages/myPackage/
    environment:
      ### from 00.commons
      # paths
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_INSTALL_HOME=${H_WMLAB_INSTALL_HOME}
      - WMLAB_SUM_HOME=${H_WMLAB_SUM_HOME}
      # switches
      - WMLAB_MONITORING_ON=${H_WMLAB_MONITORING_ON}
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_CTRL_EXEC_STDOUT_ON=${H_WMLAB_CTRL_EXEC_STDOUT_ON}
      # other parameters
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION} 
      ### locals
      - SAG_IS_LICENSE_FILE=/tmp/MSR_LICENSE.xml
      - SAG_IS_CONFIG_PROPERTIES=/tmp/application.properties
    ports:
      - ${H_WMLAB_MSR1_PORT_HOST_PORT}:5555
    entrypoint: /opt/sag/products/IntegrationServer/bin/startContainer.sh