. ..\00.commons\lib\powerShell\common.ps1

# TODO: check for credentials file first, doesn't make sense to continue if they are not there
# TODO: check if .env file exist and ask for permission to overwrite
# TODO: add optionality and mapping to dummy for optional files

$PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'

"## Lines generated by generateEnvFile.ps1" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_BPMS_UM" "Please Provide License File for Universal Messaging for BPMS" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_BPMS_BR" "Please Provide Business Rules License File" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_BPMS_MZNG" "Please Provide Mash Zone Next Generation" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_BPMS_ISPLUS" "Please Provide License File for Integration Server Plus for BPMS" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_BPMS_MSR" "Please Provide License File for Microservices Runtime" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_IP_IS" "Please Provide License File for Integration Platform - Integration Server" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_IP_UM" "Please Provide License File for Integration Platform - Universal Messaging" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_IP_TC_CLUSTERING_IS" "Please Provide License File for Integration Platform - Terracotta for Clustering" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_IP_EG" "Please Provide License File for Integration Platform - Enterprise Gateway" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_MFT_AT" "Please Provide License File for Active Transfer" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_MFT_ATG" "Please Provide License File for Active Transfer Gateway" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_API_GW_S" "Please Provide License File for API Gateway Standard Edition" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_API_GW_A" "Please Provide License File for API Gateway Advanced Edition" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_API_PORTAL" "Please Provide License File for API Portal" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_CENTRASITE" "Please Provide License File for Centrasite" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_MEDIATOR" "Please Provide License File for Mediator" >> .env
