. ..\00.commons\lib\powerShell\common.ps1

"## Lines generated by generateEnvFile.ps1" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_IP_UM" "Please Provide License File for Universal Messaging for Integration" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_IP_IS" "Please Provide License File for Integration Server" >> .env
