. ..\powerShellLib\scripts\common.ps1

# TODO: check for credentials file first, doesn't make sense to continue if they are not there
# TODO: check if .env file exist and ask for permission to overwrite
# TODO: add optionality and mapping to dummy for optional files

"## Lines generated by generateEnvFile.ps1" >> .env
generateEnvLineForFileRef "H_WMLAB_SUM11_BOOTSTRAP_BIN" "Please Provide Update Manager V11 boostrap binary file for Linux" >> .env
