version: "3.5"

services:
  centos-wm-install-helper-base:
    stop_signal: SIGINT
    image: centos-wm-install-helper
    container_name: wm-install-helper-base
    hostname: wm-install-helper-base
    volumes:
      # from 00.commons
      - ../00.commons/lib/unix:${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - ${H_RUNS_FOLDER}:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      # from 01.build.000.commons
      - ../01.build.000.commons/lib/unix:${H_WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT}
      - ${H_WMLAB_INSTALLER_BIN}:${H_WMLAB_INSTALLER_BIN_MOUNT_POINT}
      - ${H_WMLAB_PRODUCTS_IMAGE}:${H_WMLAB_PRODUCTS_IMAGE_MOUNT_POINT}
      - ${H_WMLAB_INSTALL_SCRIPT_FILE}:${H_WMLAB_INSTALL_SCRIPT_FILE_MOUNT_POINT}
      - ${H_WMLAB_SUM10_BOOTSTRAP_BIN}:${H_WMLAB_SUM10_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMLAB_SUM11_BOOTSTRAP_BIN}:${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMLAB_FIXES_IMAGE_FILE}:${H_WMLAB_FIXES_IMAGE_FILE_MOUNT_POINT}
      - ${H_WMLAB_FIXES_ONLINE_CRED_FILE}:${H_WMLAB_FIXES_ONLINE_CRED_FILE_MOUNT_POINT}
      # locals
      - ./scripts/:/mnt/scripts/local/
      - /var/run/docker.sock:/var/run/docker.sock
      # BPMS licenses
      - ${H_WMLAB_LIC_FILE_BPMS_UM}:${H_WMLAB_LIC_FILE_BPMS_UM_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_BPMS_BR}:${H_WMLAB_LIC_FILE_BPMS_BR_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_BPMS_MZNG}:${H_WMLAB_LIC_FILE_BPMS_MZNG_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_BPMS_ISPLUS}:${H_WMLAB_LIC_FILE_BPMS_ISPLUS_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_BPMS_MSR}:${H_WMLAB_LIC_FILE_BPMS_MSR_MOUNT_POINT}
      # Integration Platform licenses
      - ${H_WMLAB_LIC_FILE_IP_IS}:${H_WMLAB_LIC_FILE_IP_IS_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_IP_UM}:${H_WMLAB_LIC_FILE_IP_UM_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_IP_TC_CLUSTERING_IS}:${H_WMLAB_LIC_FILE_IP_TC_CLUSTERING_IS_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_IP_EG}:${H_WMLAB_LIC_FILE_IP_EG_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_MFT_AT}:${H_WMLAB_LIC_FILE_MFT_AT_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_MFT_ATG}:${H_WMLAB_LIC_FILE_MFT_ATG_MOUNT_POINT}
      # API Management
      - ${H_WMLAB_LIC_FILE_API_GW_S}:${H_WMLAB_LIC_FILE_API_GW_S_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_API_GW_A}:${H_WMLAB_LIC_FILE_API_GW_A_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_API_PORTAL}:${H_WMLAB_LIC_FILE_API_PORTAL_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_CENTRASITE}:${H_WMLAB_LIC_FILE_CENTRASITE_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_MEDIATOR}:${H_WMLAB_LIC_FILE_MEDIATOR_MOUNT_POINT}
      # TODO - other licenses according to use case
    environment:
      ### from 00.commons
      # paths
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_INSTALL_HOME=${H_WMLAB_INSTALL_HOME}
      - WMLAB_SUM_HOME=${H_WMLAB_SUM_HOME}
      # switches
      - WMLAB_MONITORING_ON=${H_WMLAB_MONITORING_ON}
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_CTRL_EXEC_STDOUT_ON=${H_WMLAB_CTRL_EXEC_STDOUT_ON}
      # other parameters
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION}
      ### from 01.buil.000.commons
      # mount points
      - WMLAB_INSTALLER_BIN=${H_WMLAB_INSTALLER_BIN_MOUNT_POINT}
      - WMLAB_PRODUCTS_IMAGE=${H_WMLAB_PRODUCTS_IMAGE_MOUNT_POINT}
      #- WMLAB_INSTALL_SCRIPT_FILE=${H_WMLAB_INSTALL_SCRIPT_FILE_MOUNT_POINT}
      - WMLAB_SUM10_BOOTSTRAP_BIN=${H_WMLAB_SUM10_BOOTSTRAP_BIN_MOUNT_POINT}
      - WMLAB_SUM11_BOOTSTRAP_BIN=${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - WMLAB_FIXES_IMAGE_FILE=${H_WMLAB_FIXES_IMAGE_FILE_MOUNT_POINT}
      - WMLAB_FIXES_ONLINE_CRED_FILE=${H_WMLAB_FIXES_ONLINE_CRED_FILE_MOUNT_POINT}
      - WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_FIXES_DATE_TAG=${H_WMLAB_FIXES_DATE_TAG}
      # switches
      - WMLAB_SKIP_PATCHING=${H_WMLAB_SKIP_PATCHING}
      - WMLAB_FIXES_ONLINE=${H_WMLAB_FIXES_ONLINE}
      ### locals
    entrypoint: ${H_WMLAB_ENTRY_POINT}