version: "3.5"

services:
  sum-example-1:
    image: centos-wm-install-helper
    container_name: sum-example-1
    hostname: sum-example-1
    volumes:
      # exmaple of shallower dependency towards base common projects
      # from 00.commons
      - ../00.commons/lib/unix:${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      # from 01.build.000 (take only what is needed)
      - ../01.build.000.commons/lib/unix:${H_WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT}
      - ${H_WMLAB_SUM11_BOOTSTRAP_BIN}:${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMLAB_FIXES_IMAGE_FILE}:${H_WMLAB_FIXES_IMAGE_FILE_MOUNT_POINT}
      - ${H_WMLAB_FIXES_ONLINE_CRED_FILE}:${H_WMLAB_FIXES_ONLINE_CRED_FILE_MOUNT_POINT}
      #local
      - ./scripts/:/mnt/scripts/local/
      - ${H_RUNS_FOLDER}/:${H_WMLAB_RUN_BASE_MOUNT_POINT}/
      # Base assets
      - ./inventory.json:/mnt/wm-files/inventory.json
      - ./patch.wmscript:/mnt/wm-files/patch.wmscript
      # TODO
    environment:
      ### from 00.commons (take what is needed only)
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_SUM_HOME=/opt/sag/sum
      - WMLAB_CTRL_EXEC_STDOUT_ON=${H_WMLAB_CTRL_EXEC_STDOUT_ON}
      ### from 01.build.000 (take what is needed only)
      - WMLAB_SUM11_BOOTSTRAP_BIN=${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - WMLAB_FIXES_ONLINE_CRED_FILE=${H_WMLAB_FIXES_ONLINE_CRED_FILE_MOUNT_POINT}
      - WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT}
    entrypoint: /mnt/scripts/local/entrypoint.sh