version: "3.9"

# Note: docker-compose can't substitute env vars in the service name or keys in general

volumes:
  tsa1-install-home: {}
  tsa1-sum-home: {}
  tsa1-runs: {}
  tsa1-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  tsa1:
    #network_mode: none
    image: wm-generic-host
    container_name: ${H_WMLAB_PJ_NAME}-${H_WMLAB_TSA_HOSTNAME}
    hostname: ${H_WMLAB_TSA_HOSTNAME}
    volumes:
      - tsa1-temp:/tmp/
      - tsa1-install-home:${H_WMLAB_INSTALL_HOME}
      - tsa1-sum-home:${H_WMLAB_SUM_HOME}
      # from 00.commons
      - ../00.commons/lib/unix:${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - tsa1-runs:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      # from 01.build.000
      - ../01.build.000.commons/lib/unix:${H_WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT}
      - ${H_WMLAB_INSTALLER_BIN}:${H_WMLAB_INSTALLER_BIN_MOUNT_POINT}
      - ${H_WMLAB_PRODUCTS_IMAGE}:${H_WMLAB_PRODUCTS_IMAGE_MOUNT_POINT}
      #- ${H_WMLAB_SUM10_BOOTSTRAP_BIN}:${H_WMLAB_SUM10_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMLAB_SUM11_BOOTSTRAP_BIN}:${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMLAB_FIXES_IMAGE_FILE}:${H_WMLAB_FIXES_IMAGE_FILE_MOUNT_POINT}
      - ${H_WMLAB_FIXES_ONLINE_CRED_FILE}:${H_WMLAB_FIXES_ONLINE_CRED_FILE_MOUNT_POINT}
      # locals
      - ./scripts/:/mnt/scripts/local/
      # License Related
      - ${H_WMLAB_LIC_FILE_IP_TC_CLUSTERING_IS}:${H_WMLAB_TC4CLUSTERING_LICENSE_FILE_MOUNT_POINT}
    environment:
      ### from 00.commons
      # paths
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_INSTALL_HOME=${H_WMLAB_INSTALL_HOME}
      - WMLAB_SUM_HOME=${H_WMLAB_SUM_HOME}
      # switches
      - WMLAB_MONITORING_ON=${H_WMLAB_MONITORING_ON}
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_CTRL_EXEC_STDOUT_ON=${H_WMLAB_CTRL_EXEC_STDOUT_ON}
      # other parameters
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION}
      ### from 01.build.000
      # mount points
      - WMLAB_INSTALLER_BIN=${H_WMLAB_INSTALLER_BIN_MOUNT_POINT}
      - WMLAB_PRODUCTS_IMAGE=${H_WMLAB_PRODUCTS_IMAGE_MOUNT_POINT}
      - WMLAB_INSTALL_SCRIPT_FILE=/mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/install.wmscript.txt
      - WMLAB_SUM11_BOOTSTRAP_BIN=${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - WMLAB_FIXES_IMAGE_FILE=${H_WMLAB_FIXES_IMAGE_FILE_MOUNT_POINT}
      - WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_FIXES_DATE_TAG=${H_WMLAB_FIXES_DATE_TAG}
      # switches
      - WMLAB_SKIP_PATCHING=${H_WMLAB_SKIP_PATCHING}
      - WMLAB_FIXES_ONLINE=${H_WMLAB_FIXES_ONLINE}
      ### local
      - WMLAB_TSA_HOSTNAME=${H_WMLAB_TSA_HOSTNAME}
    entrypoint: /mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/tsaSetupEntryPoint.sh  