version: "3.5"

volumes:
  tsa1-install-home: {}
  tsa1-sum-home: {}
  tsa1-sag-home: {}
  tsa1-runs: {}
  tsa1-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tsa1-data: {}

services:
  tsa1:
    image: wm-generic-host
    container_name: ${H_WMLAB_PJ_NAME}-${H_WMLAB_TSA_HOSTNAME}
    hostname: ${H_WMLAB_TSA_HOSTNAME}
    volumes:
      - tsa1-temp:/tmp/
      - tsa1-install-home:${H_WMLAB_INSTALL_HOME}
      - tsa1-sag-home:${H_WMLAB_SAG_HOME}
      - tsa1-sum-home:${H_WMLAB_SUM_HOME}
      - tsa1-data:${H_WMLAB_DATA_BASE_MOUNT_POINT}
      # from 00.commons
      - ../00.commons/lib/unix:${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - tsa1-runs:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      # locals
      - ./scripts/:/mnt/scripts/local/
      # License Related
      - ${H_WMLAB_LIC_FILE_IP_TC_CLUSTERING_IS}:${H_WMLAB_TC4CLUSTERING_LICENSE_FILE_MOUNT_POINT}
    environment:
      ### from 00.commons
      # paths
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_INSTALL_HOME=${H_WMLAB_INSTALL_HOME}
      - WMLAB_SUM_HOME=${H_WMLAB_SUM_HOME}
      - WMLAB_DATA_BASE_MOUNT_POINT=${H_WMLAB_DATA_BASE_MOUNT_POINT}
      # switches
      - WMLAB_MONITORING_ON=${H_WMLAB_MONITORING_ON}
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_CTRL_EXEC_STDOUT_ON=${H_WMLAB_CTRL_EXEC_STDOUT_ON}
      # other parameters
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION}
      ### local
      - WMLAB_TSA_HOSTNAME=${H_WMLAB_TSA_HOSTNAME}
    ports:
      - "${H_WMLAB_PJ_BASE_PORT_PREFIX}10:9510"
      - "${H_WMLAB_PJ_BASE_PORT_PREFIX}20:9887"
      - "${H_WMLAB_PJ_BASE_PORT_PREFIX}30:9443"
      - "${H_WMLAB_PJ_BASE_PORT_PREFIX}40:9889"
    entrypoint: /mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/tsaNormalEntryPoint.sh
