. ..\00.commons\lib\powerShell\common.ps1

# TODO: check for credentials file first, doesn't make sense to continue if they are not there
# TODO: check if .env file exist and ask for permission to overwrite
# TODO: add optionality and mapping to dummy for optional files

"## Lines generated by project 02.example.002.product-img-creation generateEnvFile.ps1" >> .env

generateEnvLineForFileRef "H_WMLAB_INSTALLER_BIN" "Where is the LNXAMD64 installer binary file?" >> .env
generateEnvLineForFolderRef "H_WMLAB_PRODUCT_IMAGE_DIR" "In what folder shall I save the product image?" >> .env
