version: "3.5"

volumes:
  apigw-install-home: {}
  apigw-sum-home: {}
  apigw-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  apigw:
    image: wm-generic-host
    container_name: ${H_WMLAB_PJ_NAME}-${H_WMLAB_APIGW_HOSTNAME}
    hostname: ${H_WMLAB_apigw_HOSTNAME}
    volumes:
      - apigw-temp:/tmp/
      - apigw-install-home:${H_WMLAB_INSTALL_HOME}
      - apigw-sum-home:/opt/sag/sum/
      # from 00.commons
      - ../00.commons/lib/unix:${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - ${H_RUNS_FOLDER}:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      # locals
      - ./scripts/:/mnt/scripts/local/
    environment:
      ### from 00.commons
      # paths
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_INSTALL_HOME=${H_WMLAB_INSTALL_HOME}
      - WMLAB_SUM_HOME=${H_WMLAB_SUM_HOME}
      # switches
      - WMLAB_MONITORING_ON=${H_WMLAB_MONITORING_ON}
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_CTRL_EXEC_STDOUT_ON=${H_WMLAB_CTRL_EXEC_STDOUT_ON}
      # other parameters
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION}
      ### local
      - WMLAB_APIGW_HOSTNAME=${H_WMLAB_APIGW_HOSTNAME}
    ports:
      - "${H_WMLAB_PJ_BASE_PORT_PREFIX}55:5555"
      - "${H_WMLAB_PJ_BASE_PORT_PREFIX}72:9072"
      - "${H_WMLAB_PJ_BASE_PORT_PREFIX}73:9073"
    entrypoint: /mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/apiGwNormalEntryPoint.sh
