version: "3.5"

volumes:
  mysqlce_data: {}
networks:
    n1:
      external: false
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: ${H_WMLAB_PJ_NAME}-${H_WMLAB_MYSQL_HOSTNAME} 
    hostname: ${H_WMLAB_MYSQL_HOSTNAME}
    volumes:
      - mysqlce_data:/var/lib/mysql
      - ../unixShellLib/scripts/:/mnt/scripts/lib/
      - ./runs/:${H_WMLAB_RUN_BASE_MOUNT_POINT}
    networks:
      n1:
        aliases:
          - ${H_WMLAB_MYSQL_HOSTNAME}
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${H_WMLAB_MYSQL_DATABASE_NAME}
      - MYSQL_USER=${H_WMLAB_MYSQL_USER_NAME}
      - MYSQL_PASSWORD=${H_WMLAB_MYSQL_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
      - WMLAB_MONITORING_ON=${H_WMLAB_MONITORING_ON}
    command: >
      --sql-mode="PIPES_AS_CONCAT,IGNORE_SPACE,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_FIELD_OPTIONS"
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --max_allowed_packet=128M
      --default-storage-engine=innodb
      --lower_case_table_names=1
      --innodb_buffer_pool_size=5G
      --innodb_log_file_size=80M
