version: "3.5"

networks:
    n1:
      external: false
services:
  adminer:
    image: adminer
    container_name: ${H_WMLAB_PJ_NAME}-adminer
    hostname: adminer
    networks:
      - n1
    ports:
      - "${H_WMLAB_MYSQL_ADMINER_PORT}:8080"
