version: "3.5"

networks:
    n1:
      external: false
services:
  mydbcc:
    image: mydbcc-${H_WMLAB_PRODUCTS_VERSION}
    container_name: ${H_WMLAB_PJ_NAME}-wm-dbcc-initializer
    hostname: wm-dbcc-initializer
    networks:
      - n1
    volumes:
      - ../unixShellLib/scripts/:/mnt/scripts/lib/
      - ./scripts/:/mnt/scripts/local/
      - ./runs/:${H_WMLAB_RUN_BASE_MOUNT_POINT}
    environment:
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION}
      - WMLAB_MYSQL_HOSTNAME=${H_WMLAB_MYSQL_HOSTNAME}
      - WMLAB_MYSQL_DATABASE_NAME=${H_WMLAB_MYSQL_DATABASE_NAME}
      - WMLAB_MYSQL_USER_NAME=${H_WMLAB_MYSQL_USER_NAME}
      - WMLAB_MYSQL_PASSWORD=${H_WMLAB_MYSQL_PASSWORD}
      - WMLAB_JDBC_DRIVER_URL=${H_WMLAB_JDBC_DRIVER_URL}
      - WMLAB_JDBC_DRIVER_FILENAME=${H_WMLAB_JDBC_DRIVER_FILENAME}
      - WMLAB_WM_INSTALL_HOME=${H_WMLAB_WM_INSTALL_HOME}
      - WMLAB_MONITORING_ON=${H_WMLAB_MONITORING_ON}
    entrypoint: /mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/initDbEntryPoint.sh