version: "3.8"

volumes: 
  logs: {}

services:
  msr-mock-453-prod:
    image: ${H_WMLAB_MOCK_IMAGE}
    cpuset: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
    volumes:
      - ${H_WMLAB_LIC_FILE_MSR}:/tmp/MSR_LICENSE.xml
      - ./config/application.properties:/tmp/application.properties
      - logs:/data/is/logs/
    environment: 
      - SAG_IS_LICENSE_FILE=/tmp/MSR_LICENSE.xml
      - SAG_IS_CONFIG_PROPERTIES=/tmp/application.properties
      - JAVA_MIN_MEM=256M
      - JAVA_MAX_MEM=256M
    ports:
      - ${H_WMLAB_PJ_NO}55:5555
    entrypoint: ${H_WMLAB_PRODUCTS_HOME}/IntegrationServer/bin/startContainer.sh
