. ..\00.commons\lib\powerShell\common.ps1

# TODO: check for credentials file first, doesn't make sense to continue if they are not there
# TODO: check if .env file exist and ask for permission to overwrite
# TODO: add optionality and mapping to dummy for optional files

"## Lines generated by project 00.prepare.002.fix-img-creation generateEnvFile.ps1" >> .env

#generateEnvLineForFileRef "H_WMLAB_SUM10_BOOTSTRAP_BIN" "Where is the LNXAMD64 Update Manager v10 installer binary file?" >> .env
generateEnvLineForFileRef "H_WMLAB_SUM11_BOOTSTRAP_BIN" "Where is the LNXAMD64 Update Manager v11 installer binary file?" >> .env

generateEnvLineForFolderRef "H_WMLAB_FIXES_IMAGE_DIR" "Where shall I write the images?" >> .env
