. ..\00.commons\lib\powerShell\common.ps1

"## Lines generated by generateEnvFile.ps1" >> .env
generateEnvLineForFileRef "H_WMLAB_LIC_FILE_MSR" "Please Provide License File for Microservices Runtime" >> .env
