. ..\00.commons\lib\powerShell\common.ps1

"## Lines generated by generateEnvFile.ps1" >> .env

generateEnvLineForFileRef "H_WMLAB_LIC_FILE_IP_TC_CLUSTERING_IS" "Please Provide License File for Terracotta Big Memory for Clustering.." >> .env
