version: "3.5"

volumes:
  s-1-install-home: {}
  s-1-sum-home: {}
  s-1-runs: {}
  s-1-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  s-1:
    image: wm-generic-host
    container_name: ${H_WMLAB_PJ_NAME}-${H_WMLAB_APIGW_HOSTNAME}
    hostname: ${H_WMLAB_APIGW_HOSTNAME}
    volumes:
      - s-1-temp:/tmp/
      - s-1-install-home:${H_WMLAB_INSTALL_HOME}
      - s-1-sum-home:/opt/sag/sum/
      # from 00.commons
      - ../00.commons/lib/unix:${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - s-1-runs:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      # locals
      - ./scripts/:/mnt/scripts/local/
    environment:
      ### from 00.commons
      # paths
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_INSTALL_HOME=${H_WMLAB_INSTALL_HOME}
      - WMLAB_SUM_HOME=${H_WMLAB_SUM_HOME}
      # switches
      - WMLAB_MONITORING_ON=${H_WMLAB_MONITORING_ON}
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_CTRL_EXEC_STDOUT_ON=${H_WMLAB_CTRL_EXEC_STDOUT_ON}
      # other parameters
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION}
      ### local
      - WMLAB_APIGW_HOSTNAME=${H_WMLAB_APIGW_HOSTNAME}
    ports:
      - "${H_WMLAB_PJ_BASE_PORT_PREFIX}15:5555"
      - "${H_WMLAB_PJ_BASE_PORT_PREFIX}12:9072"
      - "${H_WMLAB_PJ_BASE_PORT_PREFIX}13:9073"
      - "${H_WMLAB_PJ_BASE_PORT_PREFIX}14:9405"
      - "${H_WMLAB_PJ_BASE_PORT_PREFIX}11:5080"
    entrypoint: /mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/apiGwNormalEntryPoint.sh
