version: "3.5"

volumes:
  bpms-node-type1-install-home: {}
  bpms-node-type1-sum-home: {}
  bpms-node-type1-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
networks:
    n1:
      external: false
services:
  bpms-node-type1:
    image: wm-generic-host
    container_name: ${H_WMLAB_PJ_NAME}-bpms-node-type1
    hostname: bpms-node-type1
    networks:
      n1:
        aliases:
          - bpms-node-type1
    volumes:
      ### from 00.commons
      - ../00.commons/lib/unix:${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - ${H_RUNS_FOLDER}:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      ### locals
      - bpms-node-type1-temp:/tmp/
      - bpms-node-type1-install-home:/opt/sag/products/
      - bpms-node-type1-sum-home:/opt/sag/sum/
      - ./scripts/:/mnt/scripts/local/
    environment:
      ### from 00.commons
      # paths
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_INSTALL_HOME=${H_WMLAB_INSTALL_HOME}
      - WMLAB_SUM_HOME=${H_WMLAB_SUM_HOME}
      # switches
      - WMLAB_MONITORING_ON=${H_WMLAB_MONITORING_ON}
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_CTRL_EXEC_STDOUT_ON=${H_WMLAB_CTRL_EXEC_STDOUT_ON}
      # other parameters
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION}
      ### locals
    ports:
      - "${H_WMLAB_MWS_PORT}:8585"
      - "${H_WMLAB_IS_PORT_HOST_PORT}:5555"
      - "${H_WMLAB_UM_PORT_HOST_PORT}:9000"
      - "${H_WMLAB_AE_SERVER_PORT}:15000"
    entrypoint: /mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/node/normalEntryPoint.sh