version: "3.5"

volumes:
  bpms-node-type1-install-home: {}
  bpms-node-type1-sum-home: {}
  bpms-node-type1-temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
networks:
    n1:
      external: false
services:
  bpms-node-type1:
    image: wm-generic-host
    container_name: ${H_WMLAB_PJ_NAME}-bpms-node-type1
    hostname: bpms-node-type1
    networks:
      n1:
        aliases:
          - bpms-node-type1
    volumes:
      ### from 00.commons
      - ../00.commons/lib/unix:${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - ${H_RUNS_FOLDER}:${H_WMLAB_RUN_BASE_MOUNT_POINT}
      # from 01.build.000.commons
      - ../01.build.000.commons/lib/unix:${H_WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT}
      - ${H_WMLAB_INSTALLER_BIN}:${H_WMLAB_INSTALLER_BIN_MOUNT_POINT}
      - ${H_WMLAB_PRODUCTS_IMAGE}:${H_WMLAB_PRODUCTS_IMAGE_MOUNT_POINT}
      #- ${H_WMLAB_INSTALL_SCRIPT_FILE}:${H_WMLAB_INSTALL_SCRIPT_FILE_MOUNT_POINT}
      - ${H_WMLAB_SUM10_BOOTSTRAP_BIN}:${H_WMLAB_SUM10_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMLAB_SUM11_BOOTSTRAP_BIN}:${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - ${H_WMLAB_FIXES_IMAGE_FILE}:${H_WMLAB_FIXES_IMAGE_FILE_MOUNT_POINT}
      - ${H_WMLAB_FIXES_ONLINE_CRED_FILE}:${H_WMLAB_FIXES_ONLINE_CRED_FILE_MOUNT_POINT}
      ### locals
      - bpms-node-type1-temp:/tmp/
      - bpms-node-type1-install-home:/opt/sag/products/
      - bpms-node-type1-sum-home:/opt/sag/sum/
      - ./scripts/:/mnt/scripts/local/
      # License Related
      - ${H_WMLAB_LIC_FILE_BPMS_BR}:${H_WMLAB_LIC_FILE_BPMS_BR_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_BPMS_UM}:${H_WMLAB_LIC_FILE_BPMS_UM_MOUNT_POINT}
      - ${H_WMLAB_LIC_FILE_BPMS_ISPLUS}:${H_WMLAB_LIC_FILE_BPMS_ISPLUS_MOUNT_POINT}
    environment:
      ### from 00.commons
      # paths
      - WMLAB_RUN_BASE_MOUNT=${H_WMLAB_RUN_BASE_MOUNT_POINT}
      - WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_COMMON_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_INSTALL_HOME=${H_WMLAB_INSTALL_HOME}
      - WMLAB_SUM_HOME=${H_WMLAB_SUM_HOME}
      # switches
      - WMLAB_MONITORING_ON=${H_WMLAB_MONITORING_ON}
      - WMLAB_TAKE_SNAPHOTS=${H_WMLAB_TAKE_SNAPHOTS}
      - WMLAB_DEBUG_ON=${H_WMLAB_DEBUG_ON}
      - WMLAB_CTRL_EXEC_STDOUT_ON=${H_WMLAB_CTRL_EXEC_STDOUT_ON}
      # other parameters
      - WMLAB_PRODUCTS_VERSION=${H_WMLAB_PRODUCTS_VERSION}
      ### from 01.build.000.commons
      # mount points
      - WMLAB_INSTALLER_BIN=${H_WMLAB_INSTALLER_BIN_MOUNT_POINT}
      - WMLAB_PRODUCTS_IMAGE=${H_WMLAB_PRODUCTS_IMAGE_MOUNT_POINT}
      - WMLAB_INSTALL_SCRIPT_FILE=${H_WMLAB_INSTALL_SCRIPT_FILE_MOUNT_POINT}
      - WMLAB_SUM10_BOOTSTRAP_BIN=${H_WMLAB_SUM10_BOOTSTRAP_BIN_MOUNT_POINT}
      - WMLAB_SUM11_BOOTSTRAP_BIN=${H_WMLAB_SUM11_BOOTSTRAP_BIN_MOUNT_POINT}
      - WMLAB_FIXES_IMAGE_FILE=${H_WMLAB_FIXES_IMAGE_FILE_MOUNT_POINT}
      - WMLAB_FIXES_ONLINE_CRED_FILE=${H_WMLAB_FIXES_ONLINE_CRED_FILE_MOUNT_POINT}
      - WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT=${H_WMLAB_SETUP_SHELL_LIB_DIR_MOUNT_POINT}
      - WMLAB_FIXES_DATE_TAG=${H_WMLAB_FIXES_DATE_TAG}
      # switches
      - WMLAB_SKIP_PATCHING=${H_WMLAB_SKIP_PATCHING}
      - WMLAB_FIXES_ONLINE=${H_WMLAB_FIXES_ONLINE}
      ### locals
      - WMLAB_JDBC_DRIVER_FILENAME=${H_WMLAB_JDBC_DRIVER_FILENAME}
      - WMLAB_JDBC_DRIVER_URL=${H_WMLAB_JDBC_DRIVER_URL}
      - WMLAB_BND_FILENAME=${H_WMLAB_BND_FILENAME}
      - WMLAB_Bundle_SymbolicName=${H_WMLAB_Bundle_SymbolicName}
      - WMLAB_Bundle_Version=${H_WMLAB_Bundle_Version}
      - WMLAB_MYSQL_HOSTNAME=${H_WMLAB_MYSQL_HOSTNAME}
      #- =${}
    ports:
      - "${H_WMLAB_MWS_PORT}:8585"
      - "${H_WMLAB_IS_PORT_HOST_PORT}:5555"
      - "${H_WMLAB_UM_PORT_HOST_PORT}:9000"
      - "${H_WMLAB_AE_SERVER_PORT}:15000"
    entrypoint: /mnt/scripts/local/${H_WMLAB_PRODUCTS_VERSION}/node/setupEntryPoint.sh