. ..\00.commons\lib\powerShell\common.ps1

"## Lines generated by generateEnvFile.ps1" >> .env

generateEnvLineForFileRef "H_WMLAB_API_GW_A_LICENSE_FILE" "Please Provide License File for API Gateway Advanced " >> .env
generateEnvLineForFileRef "H_WMLAB_API_GW_S_LICENSE_FILE" "Please Provide License File for API Gateway Standard " >> .env
